### ISSUE TITLE
Repositioning Ports

### ISSUE THREAD

**Issue by sezanzeb** [MrBlenny/react-flow-chart#35]
Hi, can you please provide the SourceCode for the chart shown in the gif? https://raw.githubusercontent.com/MrBlenny/react-flow-chart/master/images/demo.gif

In particular, I would like to know how to change the ports position to the edge of the node, but I feel like I might have finally found how to: https://github.com/MrBlenny/react-flow-chart/blob/master/stories/CustomPort.tsx

Thanks.

**Comment by sezanzeb** [comment]
however, the CustomPort example also doesn't show how to reposition the ports. Overwriting props.port.position is rather clumsy as I don't see a way to tell which height the node in question has, and also the position is overwritten only after I move the viewport.

**Comment by sezanzeb** [comment]
possible solution:

```css
div[data-port-id=output] {
  position: absolute;
  bottom: -13px;
  left: -23px;
}

div[data-port-id=input] {
  position: absolute;
  top: -13px;
  left: -1px;
}
```
